import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import SiteHeader from "./components/SiteHeader";
=======
>>>>>>> ed0cd2101aeaa540f501bb7a6a53dc0c2bc0ea35
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "爱思加 IS Canada",
  description: "爱思加留学咨询官网",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> ed0cd2101aeaa540f501bb7a6a53dc0c2bc0ea35
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SiteHeader />
        <div className="pt-20">{children}</div>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> ed0cd2101aeaa540f501bb7a6a53dc0c2bc0ea35
      </body>
    </html>
  );
}
